<MyRelative>:
    RelativeLayout:
        Button:
            id: top_btn
            text: 'Top Left'
            size_hint: None, None
            size: 100, 50
            pos: 0, root.height - self.height
            on_press: root.animate_top(self)
        Button:
            id: bottom_btn
            text: 'Bottom Left'
            size_hint: None, None
            size: 100, 50
            pos: 0, 0
            on_press: root.animate_bottom(self)
